name: Build rootfs

on:
  push:
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build rootfs
        run: |
          git clone https://github.com/aarchd/arch-bootstrap --depth 1
          cd arch-bootstrap
          ./arch-bootstrap.sh -a "aarch64" -r "http://dk.mirror.archlinuxarm.org" rootfs

      - name: Pack rootfs
        run: tar czf rootfs.tar.gz rootfs

      - name: Delete previous release and tag (if exists)
        run: |
          gh release delete latest -y || true
          git push --delete origin refs/tags/latest || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: "Release"
          tag_name: "latest"
          files: rootfs.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


